version: "3.1"
services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./db:/data/db:rw
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASS}
  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVER_PORT=${SERVER_PORT}
    restart: always
    environment:
      MONGO_URI: mongodb://${MONGODB_USER}:${MONGODB_PASS}@mongo:27017/
      MONGO_DB: ${MONGODB_DATABASE}
      PORT: ${SERVER_PORT}
    depends_on:
      - mongo
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
